### ISSUE TITLE
[BUG] Issue with running the Semantic Kernel Bot

### ISSUE THREAD

**Issue by ridwanv** [Azure/AI-in-a-Box#34]
**Solution Accelerators**
This repository contains multiple solution accelerators. Please tell us which ones are involved in your report. (Replace the space in between square brackets with an x)
- [ ] Cognitive Services Landing Zone
- [X ] Semantic Kernel Bot
- [ ] Azure ML Operationalization
- [ ] Edge AI

**Describe the bug**
When running the solution locally - I get an error: 
Invalid value for 'content': expected a string, got null.\r\nStatus: 400 (model_error)\r\n\r\nContent:\r\n{\n  \"error\": {\n    \"message\": \"Invalid value for 'content': expected a string, got null.\",\n    \"type\": \"invalid_request_error\",\n    \"param\": \"messages.[8].content\",\n    \"code\": null\n  }\n}\n\r\n\r\nHeaders:\r\nAccess-Control-Allow-Origin: REDACTED\r\nX-Content-Type-Options: REDACTED\r\nx-ratelimit-remaining-requests: REDACTED\r\napim-request-id: REDACTED\r\nx-ratelimit-remaining-tokens: REDACTED\r\nX-Request-ID: REDACTED\r\nms-azureml-model-error-reason: REDACTED\r\nms-azureml-model-error-statuscode: REDACTED\r\nx-ms-client-request-id: e1043b7c-6211-442f-846d-0c34e7a3fe57\r\nx-ms-region: REDACTED\r\nazureml-model-session: REDACTED\r\nStrict-Transport-Security: REDACTED\r\nDate: Wed, 24 Jan 2024 09:39:45 GMT\r\nContent-Length: 188\r\nContent-Type: application/json\r\n"}

**To Reproduce**
1. Open Solution in Visual Studio
2. Debug solution and use the emulator
3. Emulator returns an error

**Comment by ridwanv** [comment]
Hi Marco

This happens when running from Visual STudio - using the bot framework emulator. It returns the initial turn but if I fire a question to it - when it goes to the planner it fails with the error above.

Using the chat gpt4 model hosted on Azure. 

Regards,
Ridwan

**Comment by MarcoABCardoso** [comment]
Hello @ridwanv 

This type of error tends to happen when your app is unable to reach Azure OpenAI. This may happen due to:

1. Missing appsettings.json file or missing fields within it;
2. Disabled public network access to Azure OpenAI;
3. Failed deployment of Azure OpenAI or the GPT-4 deployment.

It's unusual that you'd receive an HTTP 400 response, however. Are you sending a regular text message over Bot Framework emulator? If so, can you tell us the version you're using?

**Comment by MarcoABCardoso** [comment]
Archiving this as inactive, feel free to reopen if issue still occurs.
