### ISSUE TITLE
gpt-video-analysis-in-a-box error "Operation on target Copy GPT4 Response to Cosmos failed"

### ISSUE THREAD

**Issue by dalesayers** [Azure/AI-in-a-Box#52]
When running the ADF orchstratorGetandAnalyzeVideos pipeline, each video childAnalyzeVideo activity fails with:
 
Operation on target Copy GPT4 Response to Cosmos failed: Failure happened on 'Sink' side. ErrorCode=CosmosDbSqlApiOperationFailed,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=CosmosDbSqlApi operation Failed. ErrorMessage: Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: ();.,Source=Microsoft.DataTransfer.ClientLibrary.CosmosDbSqlApiV3,''Type=Microsoft.Azure.Cosmos.CosmosException,Message=Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ; Reason: ();,Source=Microsoft.Azure.Cosmos.Client,'

Note:  Received the following warnings during deployment:
C:\Projects\AI-in-a-Box\ai-services\gpt-video-analysis-in-a-box\infra\modules\adfpipelines.bicep(12,33) : Warning no-hardcoded-env-urls: Environment URLs should not be hardcoded. Use the environment() function to ensure compatibility across clouds. Found this disallowed host: "vault.azure.net" [https://aka.ms/bicep/linter/no-hardcoded-env-urls]
C:\Projects\AI-in-a-Box\ai-services\gpt-video-analysis-in-a-box\infra\modules\adfpipelines.bicep(74,7) : Warning use-resource-id-functions: If property "aadResourceId" represents a resource ID, it must use a symbolic resource reference, be a parameter or start with one of these functions: extensionResourceId, guid, if, reference, resourceId, subscription, subscriptionResourceId, tenantResourceId. [https://aka.ms/bicep/linter/use-resource-id-functions]
C:\Projects\AI-in-a-Box\ai-services\gpt-video-analysis-in-a-box\infra\modules\adfpipelines.bicep(595,42) : Warning BCP036: The property "Ocp-Apim-Subscription-Key" expected a value of type "string" but the provided value is of type "object".
C:\Projects\AI-in-a-Box\ai-services\gpt-video-analysis-in-a-box\infra\modules\adfpipelines.bicep(649,42) : Warning BCP036: The property "Ocp-Apim-Subscription-Key" expected a value of type "string" but the provided value is of type "object".
C:\Projects\AI-in-a-Box\ai-services\gpt-video-analysis-in-a-box\infra\modules\adfpipelines.bicep(735,48) : Warning BCP036: The property "Ocp-Apim-Subscription-Key" expected a value of type "string" but the provided value is of type "object".
C:\Projects\AI-in-a-Box\ai-services\gpt-video-analysis-in-a-box\infra\modules\adfpipelines.bicep(831,30) : Warning BCP036: The property "api-key" expected a value of type "string" but the provided value is of type "object".

**Comment by jehayesms** [comment]
I was getting that error last week as well. And struggled with it for hours when I found that for some reason, the Completion ID was returning blanks in the response and I was using that as the primary key for the Cosmos DB. Then, on Thursday and Friday, it was working returning the ID from GPT-4V! So try again now and it should be working. The fun or working with preview code.... @dalesayers

**Comment by dalesayers** [comment]
Thank you @jehayesms!,  Yes, it's working now.  Thank you so much for the excellent article and template!
