### ISSUE TITLE
Deploying to Azure, the Test in Web Chat gives an HTTP Status Internal Server Error 

### ISSUE THREAD

**Issue by DhammaParrot** [Azure/AI-in-a-Box#53]
**Solution Accelerators**
This repository contains multiple solution accelerators. Please tell us which ones are involved in your report. (Replace the space in between square brackets with an x)
- [ ] Cognitive Services Landing Zone
- [x] Semantic Kernel Bot
- [ ] Azure ML Operationalization
- [ ] Edge AI

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS: [e.g. Windows]

**Additional context**
Add any other

<img width="578" alt="Screenshot 2024-02-12 at 18 41 42" src="https://github.com/Azure/AI-in-a-Box/assets/30469752/300d91d5-5099-4404-bebb-37e736d7dc82">

**Comment by DhammaParrot** [comment]
I am not sure what is going on, I followed the step exactly :)

**Comment by DhammaParrot** [comment]
When I go to the website I get this error
<img width="1000" alt="Screenshot 2024-02-12 at 19 20 39" src="https://github.com/Azure/AI-in-a-Box/assets/30469752/65e9beca-cb7d-4d2c-b405-38d82a544db9">

**Comment by Voda88** [comment]
Getting the same error with the same steps. I can get the bot working in the emulator if I set "SSO_ENABLED": false in appsettings.json. On webchat, (with "SSO_ENABLED": true), I get 
{
  "error": {
    "code": "BadArgument",
    "message": "Missing token or secret"
  }
}

**Comment by DhammaParrot** [comment]
Why are we setting "SSO_ENABLED": true?

**Comment by MarcoABCardoso** [comment]
Hello folks!

Thank you for starting this discussion. We need to improve documentation on the SSO feature.
In short, SSO works by setting the following variables:

- SSO_ENABLED = true
- SSO_CONFIG_NAME = <name of the SSO configuration created on the Azure Bot resource>

As a result, missing SSO_CONFIG_NAME may cause issues.

@DhammaParrot can you share the deployment parameters you used? 
E.g. deploySpeech = false, deploySearch = true, etc...
Also any environment variables you changed before running the web chat.

Thank you!
Marco

**Comment by MarcoABCardoso** [comment]
Closing as stale - Feel free to reopen if the issue persists!
