### ISSUE TITLE
[BUG] Semantic Kernel Bot in-a-box document upload is not working

### ISSUE THREAD

**Issue by kdcllc** [Azure/AI-in-a-Box#55]
**Solution Accelerators**
This repository contains multiple solution accelerators. Please tell us which ones are involved in your report. (Replace the space in between square brackets with an x)
- [ ] Cognitive Services Landing Zone
- [ X] Semantic Kernel Bot
- [ ] Azure ML Operationalization
- [ ] Edge AI

**Describe the bug**
After Semantic Kernel Bot in-a-box solution is deployed or in local mode it doesn't allow for uploading of documents to chat against.

`Document upload not supported as no Document Intelligence endpoint was provided`

**Additional context**
I am creating a pull request to resolve this issue

**Comment by MarcoABCardoso** [comment]
Hello again!

After reviewing the content of the Startup.cs file, we found an error in a previous merge that removed this block - which should've been there in the first place.

I've fixed the Startup file in the latest version - would you kindly let us know if you're able to upload documents now?

Thank you!

**Comment by kdcllc** [comment]
@MarcoABCardoso yes, the upload works once the `startup.cs` is updated.

**Comment by MarcoABCardoso** [comment]
Thank you for confirming! Closing this as resolved.
