### ISSUE TITLE
[BUG] Issue with Assistant Bot deploying to azure. Works with Bot Framework Emulator but in Test Web Chat gives an 500 Internal Error

### ISSUE THREAD

**Issue by deiry** [Azure/AI-in-a-Box#57]
**Solution Accelerators**
This repository contains multiple solution accelerators. Please tell us which ones are involved in your report. (Replace the space in between square brackets with an x)
- [ ] Cognitive Services Landing Zone
- [ ] Semantic Kernel Bot
- [ ] Azure ML Operationalization
- [ ] Edge AI
- [x] Assistant Bot 

**Describe the bug**
I am using the Assistant/bot-in-a-box [project,(https://github.com/Azure/AI-in-a-Box/tree/main/gen-ai/Assistants/bot-in-a-box) This works for me locally using Bot Framework Emulator but when I go to test in the bot in "Test web chat" inside the Azure resource it does not work.

**Expected behavior**
I hope you will connect to the Assistant and answer the questions. 

**Screenshots**
This is the error I got from the app service log stream reporting about permissions issues.
<img width="1334" alt="image" src="https://github.com/Azure/AI-in-a-Box/assets/19298880/d5cba002-b064-4518-848e-ef7015bacfbb">

**Deployment Parameters:**
- deploySpeech: false
- SSO_ENABLE: false
- location:  East US 2

I am not sure if you need more info.

**Additional context**
I was comparing between the other project called SemanticKernelBot [link](https://github.com/Azure/AI-in-a-Box/tree/main/gen-ai/semantic-kernel-bot-in-a-box) and the only difference I found was that in AssistantBot you are not using the BlobServiceClient instead of SemanticKernelBot in the file _Startup.cs_
![image](https://github.com/Azure/AI-in-a-Box/assets/19298880/23ba11a3-01fa-46d1-b1b8-30f9fb6eebfb)

**Comment by MarcoABCardoso** [comment]
Hello @deiry !

Thank you for reporting this - there seems to have been an issue in merging code which caused issues when not deploying Speech.

If should be fixed in the latest version!

**Comment by deiry** [comment]
Thanks for your time! the bug is fixed!
