### ISSUE TITLE
[BUG] Issue with personal_finance example

### ISSUE THREAD

**Issue by hellseyfer** [Azure/AI-in-a-Box#61]
I have a problem with calling the functions, apparently, it's not using the call_functions method but I don't know where to put it.
This is what I get:

![image](https://github.com/Azure/AI-in-a-Box/assets/34934850/7d84792a-1950-4794-9de1-1ff77f1a3f04)

**Comment by hellseyfer** [comment]
#62 created a pull request

**Comment by codebytes** [comment]
Please try again since we merged #63 and #64
