### ISSUE TITLE
Request to update Bing resource and Semantic Kernel Library version

### ISSUE THREAD

**Issue by guru98** [Azure/AI-in-a-Box#69]
**Solution Accelerators**
This repository contains multiple solution accelerators. Please tell us which ones are involved in your report. (Replace the space in between square brackets with an x)
- [ ] Cognitive Services Landing Zone
- [ X] Semantic Kernel Bot
- [ ] Azure ML Operationalization
- [ ] Edge AI

**Describe the bug**
Bing bicep use an old configuration of bing that is deprecated. Right now bing is under cognitiveservices. Also semantic kernel libraries are not updated that means that new feature like auto invoke of functions are not available

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS: [e.g. Windows]

**Additional context**

**Comment by MarcoABCardoso** [comment]
Hello @guru98 , thank you for submitting an issue

I've re-labeled as an enhancement request as there is no associated errors.
We'll look into requirements to update the library and Bing resource.
