### ISSUE TITLE
[BUG] Issue with ...

### ISSUE THREAD

**Issue by Rishoooz** [Azure/AI-in-a-Box#89]
**Solution Accelerators**
This repository contains multiple solution accelerators. Please tell us which ones are involved in your report. (Replace the space in between square brackets with an x)
- [x] Cognitive Services Landing Zone
- [x] Semantic Kernel Bot
- [x] Azure ML Operationalization
- [x] Edge AI

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS: [e.g. Windows]

**Additional context**

**Comment by MarcoABCardoso** [comment]
This seems to an empty bug template.
Assuming this was opened by mistake, closing!
